import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import RecoilClientRoot from '@/recoil/RecoilClientRoot';
import ClientProviders from '@/components/ClientProviders';

const pretendard = localFont({
  src: '../public/fonts/PretendardVariable.woff2',
});

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={pretendard.className}>
        <ClientProviders>
          <RecoilClientRoot>
            {children}
          </RecoilClientRoot>
        </ClientProviders>
      </body>
    </html>
  );
}
